@startuml
class RelayCommand {
    + RelayCommand(execute:Action<object>, canExecute:Func<object, bool>)
    + CanExecute(parameter:object?) : bool
    + Execute(parameter:object?) : void
}
ICommand <|-- RelayCommand
@enduml
